# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(703, 414)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sayi1_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sayi1_lbl.setGeometry(QtCore.QRect(50, 40, 31, 31))
        self.sayi1_lbl.setObjectName("sayi1_lbl")
        self.sayi2_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sayi2_lbl.setGeometry(QtCore.QRect(50, 80, 41, 31))
        self.sayi2_lbl.setObjectName("sayi2_lbl")
        self.txt_sayi1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_sayi1.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.txt_sayi1.setObjectName("txt_sayi1")
        self.txt_sayi2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_sayi2.setGeometry(QtCore.QRect(100, 86, 113, 20))
        self.txt_sayi2.setObjectName("txt_sayi2")
        self.btn_topla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_topla.setGeometry(QtCore.QRect(80, 140, 101, 51))
        self.btn_topla.setObjectName("btn_topla")
        self.btn_cikar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikar.setGeometry(QtCore.QRect(190, 140, 101, 51))
        self.btn_cikar.setObjectName("btn_cikar")
        self.btn_carp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_carp.setGeometry(QtCore.QRect(310, 140, 101, 51))
        self.btn_carp.setObjectName("btn_carp")
        self.btn_bol = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bol.setGeometry(QtCore.QRect(430, 140, 101, 51))
        self.btn_bol.setObjectName("btn_bol")
        self.sonuc_lbl = QtWidgets.QLabel(self.centralwidget)
        self.sonuc_lbl.setGeometry(QtCore.QRect(100, 250, 141, 51))
        self.sonuc_lbl.setObjectName("sonuc_lbl")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sayi1_lbl.setText(_translate("MainWindow", "Sayı 1"))
        self.sayi2_lbl.setText(_translate("MainWindow", "Sayı 2"))
        self.btn_topla.setText(_translate("MainWindow", "Toplam"))
        self.btn_cikar.setText(_translate("MainWindow", "Çıkarma"))
        self.btn_carp.setText(_translate("MainWindow", "Çarpma"))
        self.btn_bol.setText(_translate("MainWindow", "Bölme"))
        self.sonuc_lbl.setText(_translate("MainWindow", "Sonuç: "))
